<a href="https://colab.research.google.com/github/Tharick15/Python-Studies/blob/main/Estudos_Pyton_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Estudos Pyton 3


1) Solicite ao usuário que informe a quantidade de linhas (n) e colunas (m) e crie um ndarray nxm com valores aleatórios.

In [ ]:
from numpy.core.fromnumeric import size
import numpy as np
n = int(input("Informe a quantidade de linhas: "))
m = int(input("Informe a quantidade de colunas: "))
array = np.random.random(size=(n,m))
array


Informe a quantidade de linhas: 3
Informe a quantidade de colunas: 2


array([[0.53262835, 0.41895391],
       [0.59633027, 0.3153888 ],
       [0.42181047, 0.78770481]])

2) Retorne a média dos valores de cada uma das n linhas

In [ ]:
linhas , colunas = array.shape
media = np.mean(array,axis = 1)
for i in range(linhas):
  print(f"A média da linha {i+1} é {media[i]}")

A média da linha 1 é 0.4757911291656559
A média da linha 2 é 0.45585953629396886
A média da linha 3 é 0.6047576428382324


3) Retorne a mediana dos valores das m colunas

In [ ]:
linhas , colunas = array.shape
mediana = np.median(array,axis = 0)
for i in range(colunas):
  print(f"A mediana da coluna {i+1} é {mediana[i]}")

A mediana da coluna 1 é 0.5326283464875325
A mediana da coluna 2 é 0.4189539118437793


4)  Dados os seguintes arrays x e y, calcula a correlação entre eles.

In [ ]:
import numpy as np
x = np.array([0, 1, 3, 8, -3])
y = np.array([5, 4, 2, 1, 7])

In [ ]:
np.corrcoef(x, y)

array([[ 1.        , -0.95320714],
       [-0.95320714,  1.        ]])

5) Faça uma função que receba um ndarray de valores inteiros e retorne um ndarray de mesma dimensão, onde os valores negativos serão substituídos por True e os valores positivos por False.

In [ ]:
import numpy as np
def array_bool():
  linhas = int(input("Qtd de linhas: "))
  vetor = []
  for i in range(linhas):
    coluna= eval('[' + input(f"Digite os valores da linha {i+1}: ") + ']')
    vetor.append(coluna)
  arr = np.array(vetor)
  print("o array de entrada foi: ", arr)
  arr_bool = arr < 0
  return arr_bool

In [ ]:
array_bool()

Qtd de linhas: 2
Digite os valores da linha 1: -1,2,6
Digite os valores da linha 2: -9,2,3
o array de entrada foi:  [[-1  2  6]
 [-9  2  3]]


array([[ True, False, False],
       [ True, False, False]])